### ISSUE TITLE
Failed when I try to test on Dart console app

### ISSUE THREAD

**Issue by NTMS2017** [giandifra/simple_rsa#11]
Hi,

As name stated I try to create a simple Dart Console app but it fails. Keep asking me to import dart.ui.

NtmsRsa is simple class in separate dart file and put some dummy text in both public and private key.

```
import 'package:simple_rsa/simple_rsa.dart';
import 'ntms_rsa.dart';
import 'dart:ui';

main(List<String> arguments) async {
  NtmsRsa _ntmsRsa = new NtmsRsa();

  String plainText = 'something';
  String encryptedText = await encryptString(plainText, _ntmsRsa.PUBLIC_KEY);
  String decryptedText = await decryptString(encryptedText, _ntmsRsa.PRIVATE_KEY);

// Test
  print(plainText);
  print(encryptedText);
  print(decryptedText);
}

```

**Comment by giandifra** [comment]
> Hi,
> 
> As name stated I try to create a simple Dart Console app but it fails. Keep asking me to import dart.ui.
> 
> NtmsRsa is simple class in separate dart file and put some dummy text in both public and private key.
> 
> ```
> import 'package:simple_rsa/simple_rsa.dart';
> import 'ntms_rsa.dart';
> import 'dart:ui';
> 
> main(List<String> arguments) async {
>   NtmsRsa _ntmsRsa = new NtmsRsa();
> 
>   String plainText = 'something';
>   String encryptedText = await encryptString(plainText, _ntmsRsa.PUBLIC_KEY);
>   String decryptedText = await decryptString(encryptedText, _ntmsRsa.PRIVATE_KEY);
> 
> // Test
>   print(plainText);
>   print(encryptedText);
>   print(decryptedText);
> }
> ```

I dont't understand, you using the package in a Flutter project or not? thanks

**Comment by NTMS2017** [comment]
yes using in flutter, but before that I try to test in dart console app

**Comment by NTMS2017** [comment]
it seems the plugin only works for flutter.
