### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'simple_rsa' is using version 1.2.30.

### ISSUE THREAD

**Issue by geGao123** [giandifra/simple_rsa#2]

**Comment by juani21** [comment]
i will update thank you

**Comment by giandifra** [comment]
fix with 0.0.2

**Comment by fenglintianxia6** [comment]
Hello bro,Android studio updated,and the problem occur again:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':simple_rsa' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51
